host boringsql_com boringsql_com 127.0.0.1 255.255.255.255 scram-sha-256
host sameuser boringsql_com 127.0.0.1 255.255.255.255 scram-sha-256
host boringsql_com boringsql_com 127.0.0.1 255.255.255.255 md5
host boringsql_com boringsql_com 127.0.0.1 255.255.255.255 password
host boringsql_com boringsql_com 127.0.0.1 255.255.255.255 trust
local boringsql_com boringsql_com scram-sha-256
local sameuser boringsql_com scram-sha-256
local boringsql_com boringsql_com md5
local boringsql_com boringsql_com password
local boringsql_com boringsql_com trust