host www_data_bene_io www_data_bene_io 127.0.0.1 255.255.255.255 scram-sha-256
host sameuser www_data_bene_io 127.0.0.1 255.255.255.255 scram-sha-256
local sameuser www_data_bene_io scram-sha-256
local www_data_bene_io www_data_bene_io scram-sha-256
local www_data_bene_io www_data_bene_io md5
local www_data_bene_io www_data_bene_io password
local www_data_bene_io www_data_bene_io trust