host samerole www_sqlservercentral_com 127.0.0.1 255.255.255.255 scram-sha-256
host www_sqlservercentral_com www_sqlservercentral_com 127.0.0.1 255.255.255.255 md5
host www_sqlservercentral_com www_sqlservercentral_com 127.0.0.1 255.255.255.255 password
host www_sqlservercentral_com www_sqlservercentral_com 127.0.0.1 255.255.255.255 trust
local samerole www_sqlservercentral_com scram-sha-256
local www_sqlservercentral_com www_sqlservercentral_com md5
local www_sqlservercentral_com www_sqlservercentral_com password
local www_sqlservercentral_com www_sqlservercentral_com trust